### ISSUE TITLE
After Scrolling Long "Blocked" Lists, JavaScript-Blocker Auto-Jumps to Top of List

### ISSUE THREAD

**Issue by tomhopper** [infernoboy/JavaScript-Blocker#16] opened 2013-06-29 16:36 UTC
![javascript-blocker screenshot](https://f.cloud.github.com/assets/472045/726191/0040a9e4-e0da-11e2-86d2-1e2aa156c5bb.png)
I have recently found that JavaScript-Blocker does not correctly scroll long lists of sites. When scrolling down a list, the list jumps back to the top of the list after a momentary pause in scrolling, making it impossible to edit sites more than about 8 sites down the "blocked" list.

See, for example, the page:
http://www.openculture.com/2013/06/ithe_atlas_of_true_namesi_restores_modern_cities_to_their_middle_earth-ish_roots.html

This page shows up with 13 blocked sites by default on my setup. About 8 items in the list show up in the JavaScript-Blocker pop-up field without scrolling. When I scroll to the bottom of the list, within a second of stopping scrolling the scroll field automatically jumps back to the top of the list.

Safari Version 6.0.5 (8536.30.1)
Mac OS X 10.8.4

**Comment by infernoboy** [comment] 2013-06-30 06:02
I am not seeing this issue on this webpage. The particular problem in question is due to the page constantly sending an updated list of allowed/blocked items. JSB does not check the new list against the previously rendered version to see if something really did change which may make it seem like it's jumping for no reason. If you can, please post the settings you are using so I can try and reproduce the issue and resolve it. Double click the "Page:" header to retrieve the necessary information.

**Comment by tomhopper** [comment] 2013-06-30 13:06
Version
3.2.11-154

Beta
0

Trial Start
-1

Trial Remaining
0,0,0

Trial Active
false

User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1

window.localStorage
{"tab":"for-ui"}

Settings
{"specialUncheckedIsCollapsed":1,"installedBundle":154,"videoUncheckedIsCollapsed":1,"donationVerified":true,"hide_imageUncheckedIsCollapsed":1,"frameUncheckedIsCollapsed":0,"setupDone":1,"trialStart":-1,"installID":"BupPYmGnMynjHkHEg~3.0.4","scriptUncheckedIsCollapsed":0,"EasyListLastUpdate":1372494524470,"LastRuleWasTemporaryIsCollapsed":0,"hide_scriptUncheckedIsCollapsed":1,"hide_embedUncheckedIsCollapsed":1,"embedUncheckedIsCollapsed":1,"hide_videoUncheckedIsCollapsed":1,"usingSnapshot":0,"isDisabled":false,"hide_frameUncheckedIsCollapsed":1,"hide_specialUncheckedIsCollapsed":1,"toggle-frame-blocked-itemsIsCollapsed":0,"allowed-script-urls-imageIsCollapsed":1,"imageUncheckedIsCollapsed":1}

Webpage
http://www.openculture.com/2013/06/ithe_atlas_of_true_namesi_restores_modern_cities_to_their_middle_earth-ish_roots.html

**Comment by infernoboy** [comment] 2013-07-01 03:09
Still not seeing this issue even when using your exact settings. Have you tried disabling other extensions to see if the issue persists? If you enable "Show number of items blocked/allowed per host" and "Show scripts that can't be blocked" under User Interface settings, do you notice if any of the numbers increment when it scrolls back up?

**Comment by infernoboy** [comment] 2013-07-10 06:54
Issue potentially resolved in the upcoming 3.3.1 update.

Edit: Issue completely resolved in 3.4.0. Updates only occur when scrolled to the top-most of the popover.

**Closed as completed by infernoboy** 2013-07-10 06:54 UTC
