### ISSUE TITLE
Blocked Scripts not shown

### ISSUE THREAD

**Issue by jasmas** [infernoboy/JavaScript-Blocker#30] opened 2014-10-20 21:41 UTC
I'm showing the following in web inspector only when javascript blocker is enabled:

[Error] Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "https://clients4.google.com". Protocols, domains, and ports must match. (x2)

Problem is this is breaking functionality of gmail and google voice and the UI itself gives no indication that this access is blocked by javascript blocker. There does not seem to be a way to create a rule allowing this access or to disable this functionality within the UI or settings. The only way to use java-script blocker with these sites at the moment seems to be to create rules disabling java-script blocker entirely for google domains.

**Comment by infernoboy** [comment] 2014-10-21 10:56
In order to attempt to reproduce the issue, I will need to use your exact settings. Please open the webpage, open the popover and double click the label "Main". Send me the information in the box that appears.

**Comment by jasmas** [comment] 2014-10-22 02:32
https://gist.github.com/jasmas/cb4d8f616d85faf2f505

**Comment by infernoboy** [comment] 2014-10-24 12:47
While I do see that message in the console, it does not break the functionality of Gmail/Google Voice for me. The messages are a result of JSB attempting to get some info from the frames on the page. Since it isn't breaking the functionality of the webpage, I have no plans of fixing this in JSB4. The issue has been mostly resolved in JSB5 already.

**Closed as completed by infernoboy** 2014-10-24 12:47 UTC
