### ISSUE TITLE
Javascript Blocker hangs Safari 8.0 (Yosemite 10.10) with 100% beachball at startup

### ISSUE THREAD

**Issue by Richard-Mlynarik** [infernoboy/JavaScript-Blocker#32] opened 2014-11-04 02:08 UTC
If I quit Safari with any open windows/tabs and then restart with Javascript Blocker enabled,
Safari 8.0 (stock Yosemite 10.10 browser, with Adblock Plus, ClickToFlash and Javascript Blocker extensions) hangs at startup.

CPU is pegged at 100% and UI is beachballed and unresponsive.

It _APPEARS_ that Javascript Blocker is attempting to pop up some whacky report or whacky dialog.

![safari startup hang](https://cloud.githubusercontent.com/assets/921288/4893787/3bd77c32-63c7-11e4-8dd2-00b11b54c680.jpg)

I'll try to add an "Activity Monitor" generated sampled backtrace once I work out how github attachments work

**Comment by Richard-Mlynarik** [comment] 2014-11-04 02:12
Oh God, one can't attach data files to bug reports.
http://stackoverflow.com/questions/10963205/how-to-attach-file-to-a-github-issue
Never mind.
I guess I'll just uninstall and delete the extension

**Comment by infernoboy** [comment] 2014-12-17 18:46
This issue is potentially resolved in 4.1.18. I can't really test it myself since I do not encounter this issue.

**Comment by dactylo** [comment] 2014-12-28 21:05
Still hangs for me with 4.1.18.

**Comment by limamedeiros** [comment] 2014-12-29 21:03
Happens the same thing to me in two different machines with Yosemite.

**Comment by infernoboy** [comment] 2014-12-30 13:57
Does this only happen during an update or does it also affect a clean install?

**Comment by limamedeiros** [comment] 2014-12-30 15:40
In my case, a clean install (I have also the following extensions installed: Adguard, Stylish and 1Password). Funny thing is I was able to get it working yesterday after installing Javascript Blocker and setting Safari to always start with a blank window. But after restarting my MacBook, every time I tried to open a site, Safari crashed. Only way to get Safari to work was to disable the extension.

**Comment by infernoboy** [comment] 2014-12-30 15:54
Can you please provide the exact steps you took when you installed it? Such as where you downloaded it from and if you installed it without having a Safari window open first. Did a popover open automatically after the install? Did the settings page automatically open? Does the hang only occur if the popover is opened?

I just can't seem to get Safari to hang/crash and without doing so am unable to fix the bugs.

**Comment by infernoboy** [comment] 2014-12-30 17:53
Can anyone see if the issue exist in this build of JSB 5? https://dl.dropboxusercontent.com/u/11967/JSB5.safariextz

Edit: It is in very early development and not intended for long-term use.

Edit 2: Rules from JSB 4 can now be imported to 5 by clicking the Rules menu.

**Comment by limamedeiros** [comment] 2015-01-03 23:47
I downloaded it from here: http://javascript-blocker.toggleable.com/downloads-2. I had a few tabs open when I installed. I don't remember a popover opening but I remember getting redirected to the settings page. 

After I install, it occurs every time that I restart Safari and set it to open the tabs from my last session. If I set it to open a empty window, I'm able to avoid the crash. But if I restart the machine and start Safari, for some reason it keeps crashing all the time I try to go to a site, no matter if I set it to start from a empty page or not, until I disable the extension. No popovers appear to me in any case.

So far JSB 5 is working ok, but I didn't restart my machine yet.

**Comment by infernoboy** [comment] 2015-01-03 23:54
Maybe if I can reproduce your settings I would be able to reproduce the issue. A quick way to do this is to open the JSB 4 popover while on a webpage and then double click the label "Main". But if this is happening after a clean install it's going to be very difficult to diagnose.

**Comment by infernoboy** [comment] 2015-01-06 16:00
Which version of Safari is this happening on? Perhaps the issue only exist in a specific version that I'm not using.

**Comment by limamedeiros** [comment] 2015-01-06 16:11
Safari 8, Yosemite 10.10.1. Don't know if it makes a difference, but both my machines are MacBooks Pro 13" from early 2011.

**Comment by infernoboy** [comment] 2015-01-06 16:12
Okay, I am downloading Yosemite and will attempt to test on this version. I've been using a newer version so hopefully this will show me what's wrong.

**Comment by infernoboy** [comment] 2015-01-06 21:09
Unfortunately I still can't reproduce this. It does hang during a new install for a few seconds, but I believe that's because of Parallels; the whole OS is very laggy. The initial install has to download the whitelist/blacklist and save it to the settings. Setting a large item like this can take a few seconds on a slower machine. This only happens once every 5 days and during new installs. This most likely isn't the problem as it doesn't make Safari crash. I am out of ideas on what to do to fix this.

**Comment by dactylo** [comment] 2015-01-07 05:00
Sorry I have almost no time to help debugging this, but as another data point, it hasn't happened for me yet on my MacBook Pro. It did happen for both accounts on a relative's iMac. All of our macs are running the latest 10.10.1 and Safari 8.0.2. For the iMac, the only way to disable the Extension (since Safari would hang on launch) was to drag out the file from Library/Safari/Extensions. Reinstalling (and not clearing the settings) would cause it to occur reproducibly every time.

**Comment by infernoboy** [comment] 2015-01-07 15:53
Do you happen to know just how long the hang lasted before force quitting Safari? Is there any chance that maybe, just maybe, something was happening really slowly and was just taking a minute or two? I know you probably can't help with that and since this appears to be happening on Yosemite only, hopefully I can just get version 5 done as quickly as possible and use that as a replacement.

**Comment by dactylo** [comment] 2015-01-07 16:09
Sure, that's possible. I probably waited around 30-60 secs.

**Comment by infernoboy** [comment] 2015-01-07 16:23
Well I'd sure hope nothing would take longer than 60 seconds regardless of the age of the Mac. I tested on my 2009 MacBook Pro and it was also just fine; no bugs to be found.

**Comment by limamedeiros** [comment] 2015-01-07 21:24
I was able to make it work but I still don't know what was the problem. I uninstalled all the extensions that I had, removed all the user settings and data from Safari. Restarted. First thing that I installed was Javascript Blocker and now it's working. I don't know if it's some incompatibility with another extension (from the ones I was using before I only reinstalled 1Password) or some odd bug with Safari.

**Comment by MartySkinner** [comment] 2015-02-01 15:02
I'm still having this issue, even after the 4.1.21 version is in play… 10.10.2 w/Safari 8.0.3.

I start Safari with only 1 window out of 6 visible, with about 40 tabs total (half in the main window). It seems that once I can activate one or more of the hidden windows (via the Window menu when I can break through the beachballs) that Safari will "recover", although sometimes it only does so after I unhide the very last window. Perhaps JB is causing something undesired to happen because the pages in the hidden windows aren't fully loaded???

I've also noticed that while Safari is 100% CPU bound that several of the WebKit processes are also taking huge amounts of CPU as well. That's partly why I think the hidden tabs are working hard at something… but not getting anywhere.

If I turn JB off, Safari doesn't get into this CPU lockup.

**Comment by a59** [comment] 2015-02-01 16:40
I have the same problem. Spinning beach ball in Safari which goes away if JavaScript Blocker is switched off. Everything was working fine for me until I upgraded to the latest Flash Player.

**Comment by ntnmrndn** [comment] 2015-02-03 17:01
I have the same problem. Somehow, it seems that installing/using google hangout plugin makes it beachball 100% of the time at startup.
I got a popup about maximum stack reached by javascript blocker, but forgot to take a screenshot.
Yosemite, last updates.

**Comment by infernoboy** [comment] 2015-02-03 17:49
ntnmrndn, if you could get that screenshot it would be immensely useful to me. I cannot pinpoint what is causing the hanging and the only reports are get are just that: Safari hangs. They all seem to be different situations, though.

**Comment by ntnmrndn** [comment] 2015-02-09 10:22
Couldn't get the screenshot however I took a stack trace during the beach balling: https://gist.github.com/ntnmrndn/22ce14c2bf06b12a26c0

**Comment by infernoboy** [comment] 2015-02-09 17:31
Unfortunately I don't really know how to interpret that in terms of how JSB's code is related to it. Seems like I'll never be able to fix this… At least JSB5 is almost done.

**Comment by ntnmrndn** [comment] 2015-02-11 03:03
Try installing googlevoice plugin (used for hangout, ...) It seems to reproduce the hang 100% of the time. I'll try to get the popup again, but just got it once :( 
I will also try to provide you with files to reproduce it.

**Comment by infernoboy** [comment] 2015-02-11 03:05
I do have it installed, but alas, no problems whatsoever.

**Comment by ntnmrndn** [comment] 2015-02-11 16:10
It just happened to me once again (about a day after the last install). 
I deleted all the files in ~/Library/Safari one by one to find the culprit.
It only worked again when I uninstalled the plugin itself (last file left in ~/Library/Safari). Last update of the file seems to be from when I installed it. Is there anywhere else where browser or plugin related files could be stored ? Reinstalling the plugin again makes it works fine.

**Comment by MartySkinner** [comment] 2015-02-11 20:55
I am very savvy but won't pretend to know how to go about looking into an extension's behaviors/interactions. If I was given some guidance on what to look into, I'd be glad to "debug" this further and I currently have lots of time to afford such an effort.

If you feel that JSB5 cannot possibly have the same (undetermined) issue(s) then the effort may be wasted on the current version.

**Comment by infernoboy** [comment] 2015-02-12 05:27
ntnmrndn mentioned that a maximum call stack error was displayed. Typically these show up pretty quickly and if anyone can get the actual error message containing the file and line number, the bug should be easy to find. Without this, I don't know where to start looking. Perhaps force quitting Safari and opening over and over again will somehow make it appear…? Technically this is supposed to automatically uninstall the extension, too. Has anyone noticed that behavior?

Again, without any indication as to what's causing the hang, there is nothing I can do. As for JSB5, since it is a complete rewrite, I do not believe it should suffer from this bug; unless it has its own version of it.

Does starting Safari without any windows/a non-webpage window still cause the hang? Also, did people experiencing the hang happen to remove the toolbar icon?

**Comment by ntnmrndn** [comment] 2015-02-12 06:28
Yes, restarting with no windows cause the hang too. And Yes I do remove the toolbar icon, will try keeping it up for a while.

**Comment by infernoboy** [comment] 2015-02-12 06:42
JSB4 won't work without its toolbar icon, but it's supposed to let you know that without completely breaking. Could this be the problem?

**Comment by ntnmrndn** [comment] 2015-02-12 06:48
Actually, I didn't knew that, and always removed the toolbar button. It works fine for a while, then hangs.
I'm trying to reproduce with a toolbar, will let you know if it hangs again.

**Comment by infernoboy** [comment] 2015-02-12 06:51
I removed the comment because it would seem the newer version doesn't bother showing the notice, but it doesn't break functionality either. I wonder… Do you have Safari's Debug menu? If so, does turning on Debug > Miscellaneous Flags > Log JavaScript Exceptions to System Console show anything in OS X's console during the hang?

**Comment by MartySkinner** [comment] 2015-02-12 19:42
I turned on the logging to Console, and ended up with loads of information dumped there. The lines that specifically pertain to JSB are [here](http://web.myspecialdomain.com/mskinner/pics/JSB%20errors.rtf). While there are many errors there, they are limited to only a few actual issues—just hit lots of times by my various tabs before I had to turn JSB off again.

Please let me know if you're looking for something else.

**Comment by infernoboy** [comment] 2015-02-12 19:58
Well the "allo[0]" errors come from the fact that JSB isn't getting a proper response from its main script. Unfortunately it would seem logging JavaScript errors only applies to webpages; it's not showing the issues from the main extension script.

**Comment by ntnmrndn** [comment] 2015-02-17 02:38
I have yet to reproduce the bug since I stopped removing js from my toolbar...

**Comment by infernoboy** [comment] 2015-02-17 23:31
If that truly is the issue then JSB5 should be immune to it as it no longer requires the toolbar icon to have popover access. Can anyone else confirm that not removing the toolbar icon prevents the hanging?

**Comment by MartySkinner** [comment] 2015-02-18 01:33
Sadly for the theory, I've never removed the toolbar icon—ever. Perhaps doing so accelerates the/an issue, but it might not be the only cause for the symptoms.

**Comment by infernoboy** [comment] 2015-02-19 03:38
Do people having the issue happen to have the setting "Ensure disabled mode persist across Safari restarts" on?

**Comment by MartySkinner** [comment] 2015-02-19 13:28
I do **not** have that setting enabled.

**Comment by infernoboy** [comment] 2015-04-14 18:49
This issue will not be fixed in version 4. Version 5 has been released and should not have this problem.

**Closed as completed by infernoboy** 2015-04-14 18:49 UTC
